
<%SUB Box_Top_Section%>

<div align='center'>
<table width=600 cellpadding=0 cellspacing=0 border=0>
<tr>
<td width=600 align=left valign=top>
<img src="/<%=Application("PGMDIR")%>/graphics/top_image.gif" width=600 height=27 alt="" border="0"></td>
</tr>
</table>
<table width=600 cellpadding=0 cellspacing=0 border=0>
<tr>
<td bgcolor="#666699" width=11 align=left valign=top><img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=5 height=5 alt="" border="0"></td>
<td bgcolor="ffffff" width=478 align=left valign=top>
<img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=478 height=1 alt="" border="0"><br>
</td>
<td bgcolor="ffffff" width=100 align=left valign=top>
<img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=100 height=7 alt="" border="0"><br>
<td bgcolor="#666699" width=11 align=left valign=top><img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=5 height=5 alt="" border="0"></td>
</tr></table>
<table width=600 cellpadding=0 cellspacing=0 border=0>
<tr>
<td bgcolor="#666699" width=11 align=left valign=top><img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=11 height=5 alt="" border="0"></td>
<td bgcolor="#ffffff" width=10 align=left valign=top><img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=10 height=5 alt="" border="0"></td>
<td bgcolor="#ffffff" width=558 align=left valign=top><br>

<%End SUB %>


<%SUB Box_Bottom_Section%>

<td bgcolor="#ffffff" width=10 align=left valign=top><img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=10 height=5 alt="" border="0"></td>
<td bgcolor="#666699" width=11 align=left valign=top><img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=11 height=5 alt="" border="0"></td>
</tr>
</table>
<table width=600 cellpadding=0 cellspacing=0 border=0>
<tr>
<td bgcolor="#666699" width=11 align=left valign=top><img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=11 height=5 alt="" border="0"></td>
<td bgcolor="ffffff" width=10 align=left valign=top><img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=10 height=5 alt="" border="0"></td>
<td bgcolor="ffffff" width=558 align=left valign=top>
<table width=95%><tr><td></center>
</td></tr></table>
</td>
<td bgcolor="#ffffff" width=10 align=left valign=top><img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=10 height=5 alt="" border="0"></td>
<td bgcolor="#666699" width=11 align=left valign=top><img src="/<%=Application("PGMDIR")%>/graphics/spacer.gif" width=11 height=5 alt="" border="0"></td>
</tr>
<tr>
<td colspan=5 width=600 align=left valign=top>
<img src="/<%=Application("PGMDIR")%>/graphics/bottom_image.gif" width=600 height=17 alt="" border="0"></td>
</tr>
</table>
</div>

<%End SUB %>
