<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^8QEAAA==o`1/:q}1P;t^3gEh+Mk^cgE:UODbxoB)[N^Z43jY.r	ob@#@&@#@&,B/4m3~WKD~W	sHPU!:Dk1/,Cx9PCxHP^4mDl1O+M/PbU~b9N^Z43jOMkUo,ckc+ ~mPO~GMP J@#@&@#@&~,PGqH,/D.Z43SPbxO/	YDB~/DD1!hjYMk	o@#@&@#@&,P~/D.1!:jOMkxL~{PODbhv1;s?DDk	o*@#@&,P~/DD/40P',E!8 &WXGR,rP'P)[9V/t0jYMkUL@#@&P~~;tnm0H!:nMk1P',KM;+@#@&@#@&,P~oKDPbUY;xYM~xP8PDW~VnUv/ODg;:UY.r	o#@#@&,P~P,~&0~bxkYDv/D.Z43S:bNcdDD1!h?DDk	LSk	Y;xODSq*#~',TP:tnU@#@&P~~,P~P,~;tn13gE:Db^P{Pol^/n@#@&PP,~P,PP,3akDPwW.@#@&~,P~P,3x9P(W@#@&P~~g+aY@#@&@#@&3	N,sjgZ:(rgB4oAAA==^#~@%>
