<%

'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^0AIAAA==@#@&@#@&wjgZK&rg~ZKx-+MY]C	o+v]+$#@#@&@#@&P,PGq\P(S,kUYwH4M~~r	YSH8M@#@&@#@&~,P/Kx7+DDImUoPxP"+5@#@&@#@&,~P&0PbUdYM`"+5~ERr#~',TP:tnU@#@&P~~,P~2o(:Po`1;Kq}1@#@&P,P3x9P(W@#@&@#@&~P,kxDoH4MP{PODrhvVn0DcI;Sr	/Y.c"+5~rRr#R8#*@#@&,P,rxDSH4MPx~DDksc:bN`"n5~bxkY.`]n$~EOrb_8#b@#@&@#@&~~,qWPbdgEhDbm`bxDo1(DbP{PWC^/+,GD,k/g;h+Mk1`rxOJg4.#,xP6lsdPK4n	@#@&P,~,P~A(&KPwjg/K&rH@#@&P~~AxN,(0@#@&@#@&~~PbxDsH4.~{PoWMhlD1;h(+Dcr	Yo1(.B!b@#@&,PPbxDJ1(D~',sG.slYg;:(+DvrUYd1(DS!b@#@&@#@&P,~q6PrUDs18.,@*~k	Od18MP:t+	@#@&~P,P~P&Px~bxYwH4M@#@&,~~P,PbxOsH8MPxPbUYd18.@#@&P~~,P~k	Od18MP{Pq@#@&,~PAx[P&0@#@&,PP;Gx7+DD]CxT+,'~JE@#@&P~PwGD,q~x,kxOog4.PDG,kUDSg4D@#@&,~P,P~ZKx-nMYImUoP',/Gx7+MY]lULP'P&~[,J~E@#@&P~~g+aY@#@&@#@&3gf,sjgZ:(rgDLMAAA==^#~@%>

