<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^IgEAAA==@#@&P~,f&HPDM\/T/SPmDz3MDWM\/T/~,dOD~l13\/L@#@&@#@&?`$PGkd2^lXm3MDGDk@#@&@#@&,P,fqtPbUYUE8@#@&@#@&~,Pq6~/DDAm^VHko,'~JE~:tnx@#@&P,P~~,/Y.$mmVHkL,'~r@!(@*Z^k1VPHW;D,JE$mm3rEP(EYDGUPDW,:C3n~1W.D^YbWUdc@!z8@*,J@#@&,~,2sk+&0PkYM$l13\/TPx~rRJ,Ptx@#@&~~P,P,/OD$C13\/T~',JE@#@&PP~3	N~q6@#@&@#@&2EkAAA==^#~@%>

<html>
<head>
<title>Data Input Errors</title>
</head>
<body>
<center>
<table width=600 cellpadding=0 cellspacing=0 border=0>
<tr>
<td width=600 align=left valign=top>
<img src="../graphics/top_image.gif" width=600 height=27 alt="" border="0"></td>
</tr>
</table>
<table width=600 cellpadding=0 cellspacing=0 border=0>
<tr>
<td bgcolor="#666699" width=11 align=left valign=top><img src="../graphics/spacer.gif" width=5 height=5 alt="" border="0"></td>
<td bgcolor="ffffff" width=478 align=left valign=top>
<img src="../graphics/spacer.gif" width=478 height=1 alt="" border="0"><br>
</td>
<td bgcolor="ffffff" width=100 align=left valign=top>
<img src="../graphics/spacer.gif" width=100 height=7 alt="" border="0"><br>
<td bgcolor="#666699" width=11 align=left valign=top><img src="../graphics/spacer.gif" width=5 height=5 alt="" border="0"></td>
</tr></table>
<table width=600 cellpadding=0 cellspacing=0 border=0>
<tr>
<td bgcolor="#666699" width=11 align=left valign=top><img src="../graphics/spacer.gif" width=11 height=5 alt="" border="0"></td>
<td bgcolor="#ffffff" width=10 align=left valign=top><img src="../graphics/spacer.gif" width=10 height=5 alt="" border="0"></td>
<td bgcolor="#ffffff" width=558 align=left valign=top><br>
   These responses were either incomplete or invalid.
   <br><br>
   <font color="#FF0000">
   <%#@~^oQAAAA==oKD~bxD?E(P{~!,KGPD.\ko/c/W!xY,Rq@#@&P,P~P~~M+dwKU/R	.bY+~c,J@!4@*'	4daiLx4kwp'x(/2iLaq02i[	8/ai[	8dwpJ,[~l.zAD.WM\/T/cr	Y?;8*P'Pr@!J4@*@!4M@*J,#@#@&P,P~Pg+aO,jSwAAA==^#~@%>
    </font>
    <br>
    <center>
    <%=#@~^CgAAAA==dDD$mm0H/T8QMAAA==^#~@%>
    </center>
</td>
<td bgcolor="#ffffff" width=10 align=left valign=top><img src="../graphics/spacer.gif" width=10 height=5 alt="" border="0"></td>
<td bgcolor="#666699" width=11 align=left valign=top><img src="../graphics/spacer.gif" width=11 height=5 alt="" border="0"></td>
</tr>
</table>
<table width=600 cellpadding=0 cellspacing=0 border=0>
<tr>
<td bgcolor="#666699" width=11 align=left valign=top><img src="../graphics/spacer.gif" width=11 height=5 alt="" border="0"></td>
<td bgcolor="ffffff" width=10 align=left valign=top><img src="../graphics/spacer.gif" width=10 height=5 alt="" border="0"></td>
<td bgcolor="ffffff" width=558 align=left valign=top>
<img src="../graphics/spacer.gif" width=558 height=25 alt="" border="0"><br>
<center><table width=95%><tr><td><center>
</center></td></tr></table></center>
<img src="../graphics/spacer.gif" width=558 height=5 alt="" border="0">
</td>
<td bgcolor="#ffffff" width=10 align=left valign=top><img src="../graphics/spacer.gif" width=10 height=5 alt="" border="0"></td>
<td bgcolor="#666699" width=11 align=left valign=top><img src="../graphics/spacer.gif" width=11 height=5 alt="" border="0"></td>
</tr>
<tr>
<td colspan=5 width=600 align=left valign=top>
<img src="../graphics/bottom_image.gif" width=600 height=17 alt="" border="0"></td>
</tr></table>
</center>
</body>
</html>

<%#@~^HwAAAA==@#@&InkwKx/RAUN@#@&31GPji~@#@&ugYAAA==^#~@%>
