<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^CAIAAA==@#@&@#@&Uj~P2slbs{AD.WM{PG|?Ea2WMY@#@&@#@&P,PGq\PdOM2hlbsHkoS~kYDo/&?;waGMY@#@&@#@&PP,/D.s;qjEawG.DP',E/!wwK.O@$6E^m.Eh^K:2EDrxTR^GsJ@#@&@#@&P~PkOM2hmk^H/TP{~/DD3:mks\koPL~JzxP`Un6a+1YnN~3MDGD,6m1E..N)E~LP-4gnSSr	+,[P74gnhdkU+@#@&~~,/YM3:mkVtdLP{PkY.2hCbV\/T~[,J3.MWD~H!:8+MxrP',+MDR	Es8+MP'P74HnSSk	n@#@&PP,dODA:mksHdL,'~/D.2slrst/o~',J3DMGMP9/1DR{J,'PD.R9+d^MkwDrW	P[,-81hdkU+@#@&@#@&~P,^l^V~jxN3hmks`kOM?\:nU+D7+MS/DDoZ&?;2aWDDS/DDZKh2l	Xglh+SdDDoZ&jEawG.D~JiU62+1ON~q+(P?bY~2MDGDr~dOM2:mrVt/o*@#@&2	N,?;4@#@&6KEAAA==^#~@%>

