<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^+QIAAA==~wjH;K&r1,2	^DHwO`kY.9mYlBdYM|+Hb@#@&@#@&,P~P9(tPrxDJW1~~r	YZUOM~~k	Owl^DWM~PbxD/xDD+@#@&@#@&~,PP&WPkYDGCOl,',JEPP4x@#@&,~P,P~~A(qP~wjHZ:(}1@#@&P,PPAx9~q6@#@&@#@&P~~,kxDol1YWM~xPtW	Y4`9CD+c#*~_,fCzvflOnv#b@#@&~,P~Ax1DXaY,xPrJ@#@&@#@&~~,PsK.PbxYdG^P{P8POW~sxc/D.fmYCb@#@&P~~,P~PbW,kUDZ	YD,',fPmx[PbxOJKmP@!~Vx`kO.3X*PPtnU@#@&~P,~P,P~~,Wx~nMDGD,./;s+,x+XY@#@&P,P~P,P~~,2x1.XaYP{~3x1DHwOP'~;C]`zjZv:r[v/Y.FXSVUv/OM|X# k	OSKmSF*#~Q,`VU`kYDnnz#,_,kUYoC1YGD*b@#@&P~~,PP~~,PrxD/	Y.,',!@#@&P,~P,P~2	N~(6@#@&,~P,PP,rUY;xDD~'~r	Y/xD.P3Pq@#@&PP~~,P~W	~D.KD,D+kEsnP	+aY@#@&~~,PP,~2	mDH2OP{PAx^Dz2DP'P;uIvbj/v:k[ckY.fmOm~r	YdWmBF*bP3PcVxcdDD|z#,_PbUOsmmDW.#b@#@&P~P,H+XY@#@&@#@&P~~,2UmMzaY~{P^+0D`AUmMX2YBFb~LPZ_]`bxYwC^YKD*P'Phr9`3x1.XaYS+*@#@&@#@&Ax[PwigZP&rgP5sYAAA==^#~@%>


<%#@~^0wIAAA==~wjH;K&r1,f^DHwO`kY.9mYlBdYM|+Hb@#@&@#@&,P~P9(tPrxDJW1~~r	YZUOM~~k	Owl^DWM~PkYM3xGlOl@#@&@#@&,PP,(0,/YM9CYmP{PEJ~P4+U@#@&~P,P~~,2((P,si1;P&rH@#@&,PP,2	[P&0@#@&@#@&~~,Pf^DHwY,x~Jr@#@&P~P~G	PnDMGD,Dnd!:+~U6O@#@&~,P~bxDsl1YK.P{P)?;`hr9`/D.fmYlB+SF*#@#@&~P~~kY.2	9lDl~x,V+WOv/ODGCDlS8#,[Psk9c/DD9lDlSf*@#@&@#@&P,PP&W~/DDAx9lOC,@!@*PrEP:tnU@#@&P~~,P~PwGMPr	YdWm,',qPDW~VxcdDD2	9lDl#@#@&~P,P,P~P~~bxOZ	OD,'~r	YZUOMPQP8@#@&P~,P,PP,P,r0,kUY;xO.,'PW~l	NPbUOSKm,@!~VnUv/OD0nX*PP4x@#@&~,P~P,~,P~,P,kxDZ	OD,'~!@#@&~~,PP,~P,P2^dn@#@&P,P~P~~,P~P,~W	Pn.MWD~./;:~	+aD@#@&PP,P,~P,P~P,P9n1DXaOP{Pf^.XaY,[~Zu]vbjZvhk9`dOM2x9CDlSk	OdW^BF*#P Pvs+	`dYM|nz*P_,rxDsl1OGD*#@#@&~P~~,P~P,~2	N~(6@#@&~~,PH+XO@#@&~,P,2x9P&W@#@&@#@&2	N~o`1Z:(rgPT7MAAA==^#~@%>
