<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>


<%#@~^agMAAA==~wjH;K&r1,MOKD[/v/O.GlYmSk	Y?DC.YqWMNSkUOg4.K.Nk#@#@&@#@&P~~,f(H,r	Y/!DBPk	YdGmBPdYMZ;.GlYm@#@&@#@&P,~~q6PkY.fCOmPxPrEPKD~rkxEhnMk^`bUD?OmDDWMN*~',0CVk+~GMPkkUEs+Db^ck	Yg4.G.9/bP{~0mVdn,KtnU@#@&~P,~,P~A(&KPwjg/K&rH@#@&P~~,2x9~qw@#@&@#@&~P,PbxOZ;.,'~!@#@&P,P~dDDZ;.GlOl,x,?OMfmYl@#@&@#@&P,P~fKPA4bV+,dYMZEM9CYmP@!@*~JE@#@&P~P,~P,kUO;ED~x,kUY;;MPQ,F@#@&P,P,~P,/OD;E.9mYl,xPDDkscdYMZ!D9lOC*@#@&P,~P,P~r	YSG^,'~k	dDDckYMZEMfmOlBJ~J*@#@&~,PP,~P&0PbUOSKm,'~!~P4+U@#@&~P,P~~,PP~r	YJW1~{Psxv/YMZ!.fmYC#,_~q@#@&P,~P,PP,~~k	Yg4.G.9/~',T@#@&P~~,PP~3	N~q6@#@&P~,P,PP&0,rxDZ;D,'@*~bxYUOlMYK.[P:tx@#@&~~,P~P,~P,MnOqWD[d,'~MOqW.9/,[P^+6O`kY.Z!D9CDl~bUYdWm qbPLPrPE@#@&~,P~P,~P,P(W,kxO/!D~'@*~bxOg4MWMNk~K4+U@#@&P~~,PP,~P,PP,3pq:PGr@#@&~~,P~P,~P,2U[,q0@#@&,P~P,~,2U9P&0@#@&P,~P,P~/DD/;MflDCP{P:b[c/DD;E.fCOm~rxDJW1_qb@#@&P~~,SGWa@#@&P~,PV+YqWM[/,'~YMkhcV+YqGD9/#@#@&31GPwjHZP(}1~AOEAAA==^#~@%>
