<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^GgMAAA==@#@&P~,PGqH,lMzZ!D(Y:d]mfmOl@#@&@#@&~ojgZ:q61~!Y(Yh/GA(U6W`]n1KzwS"+^n+H#@#@&@#@&~PV+OqD+hdGAq	WW,'P6Cs/@#@&P~qW~"+^|zP{PEE,KtnU@#@&~P,~,2p&K,sjgZ:(rg@#@&P,2U[,q0@#@&@#@&PPUnOPK4NInmG.9?nY,xPU+.-DR/.lO+}8N+^D`rbf}f~ ImGD9/nOr#@#@&~PK4L"n^WMNU+OR)^Dk-+;Gx	+^ObWx~x,/ODG8;WU	@#@&PPK4N]+1W.NU+O }w+	~/DDqDnh/:4^~~/O.G4/W	U~,l[6a+xjOmYrmB~mNJKm0n+k/bhkkYrmBPC[;:N:C4^+@#@&@#@&P,q6PUWO~K4%I^WMNjnDR26o,K4+	@#@&P~,PK4L"+1GD9?nYcHG-skMdY@#@&P,~~W(L"+^W.[U+ORwrx9PcE&Y+h(GPxPr~LP]mn+X*@#@&~P,P9W,4r^+PgGY,W4N]nmKD9?nY 3}s@#@&,~P,P~~&0PG8NInmK.9?nDRwk+^NkcJ:X2+r#~x,I+1PXa+P:4nx@#@&,P~P~~,P~lMzZ!D(O:/]n1fCYm~{PG(L"+mKD9j+D@#@&P,P~~,PP,!+DqYhdf~q	0GPx~DD;+@#@&P,P~~,PP~3oqPPG6@#@&~,P,PP,2^d+@#@&~P,P~~,PPK8L"+mK.[?YcHG\nH6O@#@&~P,P~~,2x[~&0@#@&,~,PJKWa@#@&,PAUN,qW@#@&@#@&3	NPwi1;Kq}H~09kAAA==^#~@%>
