<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^WwIAAA==o`1/:q}1PV+DKosnCY4`dOMfkMb@#@&@#@&,~~f&H,PrxOJKm@#@&@#@&P,P!nDnohKmY4P{~kY.GkM@#@&@#@&,~P&0~MYKLsnlD4P{PJr~Ptx@#@&~P~~,P!+DKosnCO4P'~];;+kOc?nM\D.mDbC4^+d`r?/]&nK|Hbt2J*@#@&P,P,P~sG.,kUYdGm,'~sx`!nDnL:hCDtb,YKPF,/Dnw,Oq@#@&P~~,PP,~P&0Psr[`V+DnL:KCDtSk	OSKmSq*P'~EJJ~WM~sk[vMYnT:hCY4~rxDSG^BF#,xPr-J,P4+	@#@&P~P~~,P~P,~PV+OKT:nCO4PxP^n6YcV+DnosnmOtBkUYdW^b@#@&P,~P,PP,~~P,2XkOPoGM@#@&P,~P,P~~,2x[~&0@#@&,~,P~,16Y@#@&,~PAVd+&0~!YnThnmYt,@!@*PrzrPPtnU@#@&~P,~P,MnOho:KCDt~',EJJ~LPV+YhosKlDt~[,J&E@#@&P,~2	NP&W@#@&,P,MnYKLsnCY4~',In5!+/O U+.\.jl.bl(V+k`rj2".3I|1)\AJ#,'PV+YhLhnmY4@#@&2H9,si1;Pq}1~YZwAAA==^#~@%>
