<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^TgIAAA==@#@&P~,PGqH,lMzZ!D]+1fCOm@#@&@#@&Pwj1;P(rgPV+OH8.GA(x6G`kY.FX#@#@&@#@&~PVnDH8Mf~qx6W,xP6ls/@#@&~,q0,dYM|+H~xPrJ,K4+U@#@&P~P,~2oqP~wj1/P&rH@#@&~,2U9P&0@#@&@#@&~PU+OPK4%]mWM[?YP{~j+M\D Z.nmYnr(%+1YcEzfr9$cInmK.9/nDJ*@#@&,PK8L"+^WMNjnDRranx,/YM\8DkK(VSPdOMf8ZKUxBPC[}w+UjDlOk1S,l[dW13n/kr:b/Ok1~~C9Z:9Pl(V+@#@&@#@&,P&0~xGO,W8L"nmKD[jYR36wPPtU@#@&~,P,W4NI^WMNj+DR\G7+sb./D@#@&,~~PK4NInmG.9?nYcok	N~cr+O\CbV~',vrP',YMk:v/D.|XbPLPEvr#@#@&~P,Pq6~UWDPK4%In^KD[?ORAro~:t+U@#@&P~P,~,PCMX;ED"+19lDl~',W8%"+mK.NU+Y@#@&~P,P,P~MnOt4.f~(x6W~x,YD;n@#@&~P,~Ax[,q6@#@&,PAUN,qW@#@&@#@&3	NPwi1;Kq}H~PKEAAA==^#~@%>
