<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^RgIAAA==@#@&P~,PGqH,lMzZ!D]+6In^GlYm@#@&@#@&PwiHZ:q}1~MnO"+Wf~(x6Wcr	Y|nz*@#@&@#@&~,MnDI0f~q	WW,'~0mVdn@#@&P,(0,kxDFnX,',JEPP4x@#@&,~P,P3p&KPoigZPq}H@#@&~,2	NP&0@#@&@#@&P~?Y~G(LI^WMN?O~',?D-+. ;DnlDnr(Ln^D`J)9}f$R"n1W.9/YJ*@#@&~PK4%ImG.9?+D ra+x,dOD"+6K8VS~kY.f(/W	xS~mNr2n	?OlDr1~~mNdWm0nd/b:r/Dk^S,lN;hN:l4^n@#@&@#@&,P(0~UKY~W(%ImG.9?+O AroP:4x@#@&P,PPK4N]+1W.NU+O tW\okM/Y@#@&~P,PK4%In^KD[?ORwkU[,`J(9,'~J,',kUD|X#@#@&,~P,P(0,xGO,W4N]+1WD9jnYc2}s~K4n	@#@&P,~P,P~~mDX/;MIn0"n1fCDl,'PK4N]+1W.NU+O@#@&PP,~P,PPVnOI0GA(xWG,'~YM;+@#@&~~,PP3U9P(0@#@&,P3	N,q0@#@&@#@&2	N~s`1/P&r1,vJ4AAA==^#~@%>
