<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^yQEAAA==~wjH;K&r1,nz9`kY.fmYCSbxYdnxB/YM9rD*@#@&@#@&P~~,f(H,rxDZUOM@#@&@#@&,P~Ph)GPx,/DDfmYm@#@&,P~PbxOJx'wGDslYg;h4DvkUYJn	#@#@&@#@&P,P~(6PVnUv/ODGCDlb@*PbxYd+	~K4+U@#@&P~~,PP,KbGP',sn0D`kY.fCOm~rxDJ+	#@#@&,PP~~,P3(&P,sigZ:qrg@#@&~P,P3x9P(W@#@&@#@&~P,PsK.~k	Y;xOD~x,VnxvdYMfCOm#_q~DW~k	Od+U@#@&,PP,P,~q6PdYMfr.,'Pr]J,KtU@#@&,P,P~P~~,PKbG~',n)9,[PE~r@#@&P,~,P~,2^/+@#@&,~P,P~P,P~vG+0m;VD@#@&,~~P,P,P~PK)GPxPr~J,[~Kzf@#@&~,P~P,~Ax[,q6@#@&,P,~16O@#@&2H9,sjg/K&r1,1GcAAA==^#~@%>
