<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^bgIAAA==@#@&@#@&,P,fqtPbUYg4.I0orVNk@#@&,PPG(\PbxDIn0(9BPdYM]+6Kz2~PdOMIn0gCs+S,/DDI0jCV!+SPkY.]0fbdw^lXUn5@#@&P,P9q\~bxOIWqGIn^BPkUO"+WKH2In1~,kxDIW1m:nImS~bxY"n0jlV!n]+1~,kUY]n6fr/aslH?n5"+m@#@&@#@&~P,r	YH(D"+0wksNkPxPZ@#@&~,Pk	OI0qG]nm,',kUYH8MIn0wr+^Nd@#@&@#@&~~,kUYg8MIn6sb+V9/,xPbxO1(D]n6sksNkP_,q@#@&,P,kUY]n6Kzw]+1Px~bxYH8MIn0wrV[k@#@&@#@&,P,rxD18D"+Wob+V9dP{Pk	OH4MI0okns9/~_,q@#@&P~~bxY]n61C:]m~{PbxYg4M]+6sr+^Nd@#@&@#@&@#@&P,Pk	OH4MI0okns9/~',rxD18."+0orV[/,Q,F@#@&P,Pk	Y"n0Gkdw^lzj;I^P{Pk	OH4MI0okns9/@#@&@#@&P,PrUD14.]0oks9/~{PbxYg4M]+6sr+^Nd~3PF@#@&P,Pk	O]+6.mV;+]n1PxPbUYg4.]0srn^Nd@#@&@#@&MbgAAA==^#~@%>


