<%SUB Build_Link_Group_Array
aryLinkGroup(1,1) = "Antique Textiles and Textile Care"
aryLinkGroup(1,2) = 11
aryLinkGroup(2,1) = "Weaving Books ( Bibliography)"
aryLinkGroup(2,2) = 10
aryLinkGroup(3,1) = "Weaving Supplies"
aryLinkGroup(3,2) = 12
aryLinkGroup(4,1) = "Weaving Organizations & Schools"
aryLinkGroup(4,2) = 13
aryLinkGroup(5,1) = "Miscellaneous Resources"
aryLinkGroup(5,2) = 14
aryLinkGroup(0,0) = 5
END SUB%>
