<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^7QAAAA==@#@&f(tPkYD;EM3xDDz~,/O.UYlDnnM~PkO.ZKE	Y.XK.@#@&@#@&UiA,?OCD+{jn^+^YbG	{Jb/D@#@&@#@&,~P&0~/DDjOmY+h.P{PJr~Ptx@#@&~P~~,PdYMjYmYnKMP'~EUYCYE@#@&~,PAxN,q6@#@&,P~q6PdOMZW!UYMXnM~xPrJ,K4+U@#@&P~P,~PkY./KExO.Hn.P{~rZG!xDDXr@#@&~P,2UN,qW@#@&cT8AAA==^#~@%>

<select name="<%=#@~^CgAAAA==dDDjDlD+nMHAQAAA==^#~@%>" size="1">
<option selected value=<%=#@~^IAAAAA==/_Ic2c*P[,/D.Z!D3xDDz~LPZ_]`2c#,qwgAAA==^#~@%>><%=#@~^DQAAAA==~kY.;EM2xDDH~1QQAAA==^#~@%>
<option value=""></option>
<option value="AL">AL</option>
<option value="AK">AK</option>
<option value="AZ">AZ</option>
<option value="AR">AR</option>
<option value="CA">CA</option>
<option value="CO">CO</option>
<option value="CT">CT</option>
<option value="DE">DE</option>
<option value="DC">DC</option>
<option value="FL">FL</option>
<option value="GA">GA</option>
<option value="HI">HI</option>
<option value="ID">ID</option>
<option value="IL">IL</option>
<option value="IN">IN</option>
<option value="IA">IA</option>
<option value="KS">KS</option>
<option value="KY">KY</option>
<option value="LA">LA</option>
<option value="ME">ME</option>
<option value="MD">MD</option>
<option value="MA">MA</option>
<option value="MI">MI</option>
<option value="MN">MN</option>
<option value="MS">MS</option>
<option value="MO">MO</option>
<option value="MT">MT</option>
<option value="NE">NE</option>
<option value="NV">NV</option>
<option value="NH">NH</option>
<option value="NJ">NJ</option>
<option value="NM">NM</option>
<option value="NY">NY</option>
<option value="NC">NC</option>
<option value="ND">ND</option>
<option value="OH">OH</option>
<option value="OK">OK</option>
<option value="OR">OR</option>
<option value="PA">PA</option>
<option value="PR">PR</option>
<option value="RI">RI</option>
<option value="SC">SC</option>
<option value="SD">SD</option>
<option value="TN">TN</option>
<option value="TX">TX</option>
<option value="UT">UT</option>
<option value="VT">VT</option>
<option value="VA">VA</option>
<option value="WA">WA</option>
<option value="WV">WV</option>
<option value="WI">WI</option>
<option value="WY">WY</option>
<option value="AE">AE</option>
<option value="AP">AP</option>
<option value="AA">AA</option>
<option value="AS">AS</option>
<option value="FM">FM</option>
<option value="GU">GU</option>
<option value="MH">MH</option>
<option value="MP">MP</option>
<option value="PW">PW</option>
<option value="VI">VI</option>
</select>
<%#@~^CQAAAA==~Ax[,?`APYQIAAA==^#~@%>

<%#@~^GgAAAA==j`A~;W!xYMX|j+^+^YbWUmdk/D/gkAAA==^#~@%>

<select name="<%=#@~^DAAAAA==dDD/KE	YDHnMDwUAAA==^#~@%>" size="1">
 <option selected value=<%=#@~^IAAAAA==/_Ic2c*P[,/D.Z!D3xDDz~LPZ_]`2c#,qwgAAA==^#~@%>><%=#@~^DQAAAA==~kY.;EM2xDDH~1QQAAA==^#~@%>
 <option value="United States">United States</option>
 <option value="Angola">Angola</option>
 <option value="Argentina">Argentina</option>
 <option value="Austria">Austria</option>
 <option value="Australia">Australia</option>
 <option value="Belgium">Belgium</option>
 <option value="Bolivia">Bolivia</option>
 <option value="Brazil">Brazil</option>
 <option value="Canada">Canada</option>
 <option value="Chile">Chile</option>
 <option value="China">China</option>
 <option value="Columbia">Columbia</option>
 <option value="Czech Republic">Czech Republic</option>
 <option value="Denmark">Denmark</option>
 <option value="Egypt">Egypt</option>
 <option value="England">England</option>
 <option value="Estonia">Estonia</option>
 <option value="Finland">Finland</option>
 <option value="France">France</option>
 <option value="Ghana">Ghana</option>
 <option value="Germany">Germany</option>
 <option value="Greece">Greece</option>
 <option value="Hong Kong">Hong Kong</option>
 <option value="Hungary">Hungary</option>
 <option value="Iceland">Iceland</option>
 <option value="India">India</option>
 <option value="Indonesia">Indonesia</option>
 <option value="Iran">Iran</option>
 <option value="Ireland">Ireland</option>
 <option value="Israel">Israel</option>
 <option value="Italy">Italy</option>
 <option value="Jamaica">Jamaica</option>
 <option value="Japan">Japan</option>
 <option value="Korea">Korea</option>
 <option value="Latvia">Latvia</option>
 <option value="Lithuania">Lithuania</option>
 <option value="Malaysia">Malaysia</option>
 <option value="Mexico">Mexico</option>
 <option value="Micronesia">Micronesia</option>
 <option value="Nambia">Nambia</option>
 <option value="New Zealand">New Zealand</option>
 <option value="Nigeria">Nigeria</option>
 <option value="Norway">Norway</option>
 <option value="Paraguay">Paraguay</option>
 <option value="Philippines">Philippines</option>
 <option value="Poland">Poland</option>
 <option value="Portugal">Portugal</option>
 <option value="Puerto Rico">Puerto Rico</option>
 <option value="Romania">Romania</option>
 <option value="Russia">Russia</option>
 <option value="Saudi Arabia">Saudi Arabia</option>
 <option value="Scotland">Scotland</option>
 <option value="Seychelles">Seychelles</option>
 <option value="Singapore">Singapore</option>
 <option value="South Africa">South Africa</option>
 <option value="Spain">Spain</option>
 <option value="Sweden">Sweden</option>
 <option value="Switzerland">Switzerland</option>
 <option value="Tabago">Tabago</option>
 <option value="Taiwan">Taiwan</option>
 <option value="The Netherlands">The Netherlands</option>
 <option value="Thialand">Thialand</option>
 <option value="Trinidad">Australia</option>
 <option value="Turkey">Turkey</option>
 <option value="UAE">UAE</option>
 <option value="United Kingdom">United Kingdom</option>
 <option value="United States">United States</option>
 <option value="Uruguay">Uruguay</option>
 <option value="Venezuela">Venezuela</option>
 <option value="Zaire">Zaire</option>
 <option value="Zimbabwe">Zimbabwe</option>
</select>
<%#@~^CAAAAA==3	N~Uj~PQQIAAA==^#~@%>
