<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^swAAAA==~Uj$,MkY{:.l	/W+M{uPtS`hCoSW1b@#@&@#@&Gq\PdOMnCoJW1@#@&@#@&q0~r	/ODvKmondW1~J=zJE#,@*~!,K4n	@#@&kODhloJGm,',nConJKm@#@&As/@#@&dDDnCLSGm,x,J4DYa)zJJ,'PhlL+dW^@#@&2x9~q6@#@&,Dy8AAA==^#~@%>

<head>
<meta http-equiv="Refresh" content="0; url=<%=#@~^CwAAAA==dDDKmoSW1PFAQAAA==^#~@%>">
</head>
<body>
</body>
</html>

<%#@~^HAAAAA==@#@&InkwKx/RAUN@#@&31GPji~PwwYAAA==^#~@%>

