<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^nQIAAA==~wjH;K&r1,.msk9lO+hlddSWD9oWM:lDcdYMnkh[#@#@&,P~P,~@#@&P~~&0PdOMndh9~{PErP:t+	P,~P,P@#@&,P~~,P2o(K,sjg/Pq}1@#@&~P~3	N~q6@#@&,P~(6PVnUv/ODhdSNb,@!,cP:tU@#@&P~P,P~#mVk9CYnlkdAWMNwW.:CO,'~JhC/khG.9PH;dDP8+,CDPJlkYPWPg;:(+./,W.~d+YDnDkJ@#@&~~P,P,2pqP~wjHZ:(rg@#@&~,P2sd@#@&P,~,P~kYMK+sw,xPr!q 2cXF%,r@#@&,PP,~~sKD,q~'~lPOW,1!@#@&~~,PP~~,PdYMP:2,',/YMKhw,[~Z_Ic(*@#@&,~P,PPgnaY@#@&,P~P~~wW.P&~',F~PKPVnUv/ODhdSNb@#@&,PP,P,~P,qWPbxdOM`/D.K:wBhrNvj;ld+cdDDK/S[#BqSq*#Px~ZPPtU@#@&~,P,PP,P,~P,.CVbNCOnlkdhKDNwG.:mY,'~JKCk/AWM[PtEdO,4+~/K:8k	CDkG	PK0PgEs8+M/&SYOnM/P}UVHJ@#@&~~P,P,P~P~~,2pq:~s`1/P&r1@#@&,P~P,~,P~Ax9Pq6@#@&~P,P~Pg+aO@#@&P,~2	NP&W@#@&@#@&A19PoigZPq}HPpKgAAA==^#~@%>
