<%
'          **************************************************
'          *  Copyright Fulcrum Computing, Inc.  2000       *
'          **************************************************
'          * This program is copyrighted under the laws of  *
'          * the United States. Any unautorized duplication *
'          * or use of this progrm is prohibited.           *
'          **************************************************
'**Start Encode**#@~^BAAAAA==@#@&FwAAAA==^#~@%>

<%#@~^FwMAAA==~wjH;K&r1,.msk9lO+AHCr^sWMhlD`/D.3Hmk^b[N.nk/b@#@&~P,P~~@#@&P~~Gq\PkOM.C^k9ZtmDkSPbxOZ	Y.~,P@#@&~P,PP,@#@&P,Pjlsk[CD+3HmrVwW.hmYPx~DD;+,~,@#@&,P,@#@&,P,rxDZUYMPx~bx/D.`kYDA\Ck^b9N.+ddBJ@$J*@#@&,P~@#@&PP~(6PrxD/	Y.,',!P:tUP,P~P,@#@&~,PP,~.mVk9CO+AHmkssG.slOP{~0mVdn@#@&P~~AVd+&W,kUkYM`k	Y;UYM~dYM2\CbVb9[D//BE J*P{PTPP4x@#@&,~P,P~#mVk[CD+3Hmr^sGM:mYP{P6CVk+@#@&,P~3^/+@#@&P,PP,~dYM.mVrN/4mDdP,xPr!q+2c*{R, { @$r@#@&,P,PP,sK.PbxOZ	Y.~{Pvl~YKP,Z@#@&P,P,P~P~~kY..msk9Z4CM/P~x,/ODjC^k[;tmD/,PL~Z_Ick	Y/UDD#@#@&P,PP,~H+XY@#@&~P~~,PoWM~k	Y/UDDPx~8PPW,sxckYM2Hmk^)N9Dn/k#@#@&,PP,~P,PP&W~k	/DDc/O.jlsk9/tmDd~B:k[c`ZC/ckY.AHmkVzN9.+k/b~bxO/	YDBq#*P',T~K4+	@#@&P~~,P~P,~P,P#C^kNCO2\lbswW.slDP',0ms/@#@&P,P~~,PP,~P,2(&P~s`1;K(rH@#@&P~P,~P,P~3	NP(W@#@&~P,~,PH6D@#@&,P,3x9P(0@#@&@#@&A1f,ojgZK&6HPH80AAA==^#~@%>
